/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;
import static org.junit.Assert.assertEquals;
import org.junit.Test;


public class AppTest {
    @Test public void returnnumbers(){
        App testapp = new App();
        assertEquals(4, testapp.returnnumbers());
    }
}
